# General info
site_name: Anasme's Docs
site_description: Mon site agrégateur de docs orienté DevOps/AdminSYS
site_author: Anas Asmi
site_url: https://anasme.github.io/docs
markdown_extensions:
  - admonition

# Repos   
repo_name: anasme/docs
repo_url: https://github.com/Anasme/docs

# Copyright
copyright: '© Anas Asmi 2018'

#Config
theme:
  name: 'material'
  palette:
    primary: 'light-blue'
    accent: 'deep-orange'
  font:
          #text: 'Concert One regular'
          #text: 'Nunito Semibold'
          #text: 'Bubblegum Sans'
    text: 'Quicksand'
    code: 'Exo 2'
  logo: 
  #icon: 'whatshot'
    icon: 'fingerprint'
    favicon: 'whatshot'
  language: 'fr'
  feature:
    tabs: true

# Customization
extra:
  social:
    - type: github-alt
      link: https://github.com/anasme
    - type: twitter
      link: https://twitter.com/anasasmi
    - type: linkedin
      link: https://linkedin.com/in/anasasmi
  disqus: 'anasmedocs'
# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Google Analytics
google_analytics:
  - UA-112015225-2
  - auto
