# General info
site_name: Anasme's Docs
site_description: Mon site agrégateur de docs orienté DevOps/AdminSYS
site_author: Anas Asmi
site_url: https://
markdown_extensions:
  - admonition

# Repos   
repo_name: anasme/docs
repo_url: https://github.com/Anasme/docs

# Copyright
copyright: '© Anas Asmi 2018'

#Config
theme:
  name: 'material'
  palette:
    primary: 'Cyan'
    accent: 'deep-orange'
  font:
    text: 'Courgette'
    code: 'Quicksand'
  logo: 
  #icon: 'whatshot'
    icon: 'fingerprint'
    favicon: 'whatshot'
  language: 'fr'
  feature:
    tabs: true

# Customization
extra:
  social:
    - type: github-alt
      link: https://github.com/anasme
    - type: twitter
      link: https://twitter.com/anasasmi
    - type: linkedin
      link: https://linkedin.com/in/anasasmi

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Material: index.md
  - Getting started: getting-started.md
  - Extensions:
    - Admonition: extensions/admonition.md
    - CodeHilite: extensions/codehilite.md
    - Footnotes: extensions/footnotes.md
    - Metadata: extensions/metadata.md
    - Permalinks: extensions/permalinks.md
    - PyMdown: extensions/pymdown.md
  - Specimen: specimen.md
  - Customization: customization.md
  - Compliance with GDPR: compliance.md
  - Release notes: release-notes.md
  - Author's notes: authors-notes.md
  - Contributing: contributing.md
  - License: license.md

# Google Analytics
google_analytics:
  - !!python/object/apply:os.getenv ["GOOGLE_ANALYTICS_KEY"]
  - auto
